<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>The Won Cause by Barbara A Gannon</title>
	<style type="text/css">
		@import url("css/reset.css");
		@import url("css/styles.css");
		@import url("css/appendices.css");
	</style>
</head>

<body>
	<div id="page_container">
    	<div id="header_container">
            <h1>The Won Cause by Barbara A. Gannon</h1>
            <p id="description">
            	The Won Cause is a book about black and white Civil War veterans and their comradeship in the Grand Army of the Republic (GAR)—the Union Army’s largest veterans’ organization. You may not know the GAR, but you do know its modern counterparts: the American Legion, the Veterans of Foreign Wars, and the Iraq and Afghanistan Veterans of America. The GAR was the precursor of these groups, the first nationwide veterans’ organization. It originated in the immediate aftermath of the Civil War when a handful of Union Army veterans formed the first GAR post, or local veterans’ group, in Decatur, Illinois. From these small beginnings, the GAR grew until it enrolled hundreds of thousands of black and white members in posts all across America. The GAR welcomed former soldiers and sailors who had received an honorable discharge from the U.S. Army or Navy during the Civil War. During its heyday, the GAR was the nation’s largest social and charitable organization, with all the political power inherent in representing such a large membership. Remarkably, the largest and most powerful social organization of the nineteenth century was an interracial group.
            </p>
            
        	<div id="mural">
            	<img src="images/mural_opaque.png" alt="The Won Cause Mural" title="The Won Cause Mural" />
            </div><!--nav_container-->
            <a name="top"></a>
		<?php
			include("navigation.php");
		?>
        </div><!--header_container-->
        <div id="content_container">
		<?php
			include_once("left_bar.php");	
			include_once("right_bar.php");
		?>
          	<div id="appendices_container">
				<h2><a name="appendix_1"></a>Appendix 1 - African American GAR Posts</h2>
				<div id="alpha_order">
					<a href="#a">A</a>
					<a href="#b">B</a>
					<a href="#c">C</a>
					<a href="#d">D</a>
					<a href="#e">E</a>
					<a href="#f">F</a>
					<a href="#g">G</a>
					<a href="#h">H</a>
					<a href="#i">I</a>
					<a href="#j">J</a>
					<a href="#k">K</a>
					<a href="#l">L</a>
					<a href="#m">M</a>
					<a href="#n">N</a>
					<a href="#o">O</a>
					<a href="#p">P</a>
					<a href="#q">Q</a>
					<a href="#r">R</a>
					<a href="#s">S</a>
					<a href="#t">T</a>
					<a href="#u">U</a>
					<a href="#v">V</a>
					<a href="#w">W</a>
					<a href="#x">X</a>
					<a href="#y">Y</a>
					<a href="#z">Z</a>
				</div>
				<table>
					<thead>
						<th id="state">State</th>
						<th id="post_no">Post No.</th>
						<th id="name">Name</th>
						<th id="location">Location</th>
					</thead>
					<tbody>
						<tr class="alpha_gap">
							<td><a name="a"></a>A</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Arkansas</td>
							<td>7</td>
							<td>Judson</td>
							<td>Little Rock</td>
						</tr>
						<tr>
							<td></td>
							<td>23</td>
							<td>Sumner</td>
							<td>Fort Smith</td>
						</tr>
						<tr>
							<td></td>
							<td>30</td>
							<td>Washington</td>
							<td>Hot Springs</td>
						</tr>
						<tr>
							<td></td>
							<td>103</td>
							<td>Hutchinson</td>
							<td>Brinkley</td>
						</tr>
						<tr>
							<td></td>
							<td>121</td>
							<td>Shaw</td>
							<td>Marianna</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="d"></a>D</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>District of Columbia</td>
							<td>4</td>
							<td>Morton</td>
							<td>Washington, D.C.</td>
						</tr>
						<tr>
							<td></td>
							<td>9</td>
							<td>Sumner</td>
							<td>Washington, D.C.</td>
						</tr>
						<tr>
							<td></td>
							<td>21</td>
							<td>Douglass</td>
							<td>Washington, D.C.</td>
						</tr>
						<tr>
							<td>Delaware</td>
							<td>7</td>
							<td>Judson</td>
							<td>Little Rock</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="f"></a>F</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Florida</td>
							<td>6</td>
							<td>Gabriel</td>
							<td>Jacksonville</td>
						</tr>
						<tr>
							<td></td>
							<td>14</td>
							<td>Logan</td>
							<td>St. Augustine</td>
						</tr>
						<tr>
							<td></td>
							<td>18</td>
							<td>Montgomery</td>
							<td>Palatka</td>
						</tr>
						<tr>
							<td></td>
							<td>22</td>
							<td>Hunter</td>
							<td>Tallahassee</td>
						</tr>
						<tr>
							<td></td>
							<td>23</td>
							<td>Stephenson</td>
							<td>Pensacola</td>
						</tr>
						<tr>
							<td></td>
							<td>30</td>
							<td>Hamel</td>
							<td>South Jacksonville</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="g"></a>G</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Georgia</td>
							<td>8</td>
							<td>Shaw</td>
							<td>Savannah</td>
						</tr>
						<tr>
							<td></td>
							<td>15</td>
							<td>Delany</td>
							<td>Brunswick</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="i"></a>I</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Illinois</td>
							<td>50</td>
							<td>Brown</td>
							<td>Chicago</td>
						</tr>
						<tr>
							<td></td>
							<td>233</td>
							<td>Shaw</td>
							<td>Quincy</td>
						</tr>
						<tr>
							<td></td>
							<td>578</td>
							<td>Bross</td>
							<td>Springfield</td>
						</tr>
						<tr>
							<td></td>
							<td>598</td>
							<td>Foster</td>
							<td>Cairo</td>
						</tr>
						<tr>
							<td></td>
							<td>599</td>
							<td>Cobb</td>
							<td>Metropolis</td>
						</tr>
						<tr>
							<td></td>
							<td>630</td>
							<td>Mound City</td>
							<td>Mound City</td>
						</tr>
						<tr>
							<td></td>
							<td>663</td>
							<td>Delany</td>
							<td>Chicago</td>
						</tr>
						<tr>
							<td></td>
							<td>687</td>
							<td>Governor Yates</td>
							<td>Jacksonville</td>
						</tr>
						<tr>
							<td></td>
							<td>728</td>
							<td>Murphysboro</td>
							<td>Murphysboro</td>
						</tr>
						<tr>
							<td></td>
							<td>749</td>
							<td>Pennock East</td>
							<td>St. Louis</td>
						</tr>
						<tr>
							<td>Iowa</td>
							<td>413</td>
							<td>Pratt</td>
							<td>Keokuk</td>
						</tr>
						<tr>
							<td>Indiana</td>
							<td>70</td>
							<td>Delany</td>
							<td>Indianapolis</td>
						</tr>
						<tr>
							<td></td>
							<td>351</td>
							<td>Penney</td>
							<td>Jeffersonville</td>
						</tr>
						<tr>
							<td></td>
							<td>541</td>
							<td>Grills</td>
							<td>Evansville</td>
						</tr>
						<tr>
							<td></td>
							<td>556</td>
							<td>King David</td>
							<td>Mount Vernon</td>
						</tr>
						<tr>
							<td></td>
							<td>581</td>
							<td>Fort Wagner</td>
							<td>Evansville</td>
						</tr>
						<tr>
							<td></td>
							<td>585</td>
							<td>Brown</td>
							<td>Charlestown</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="k"></a>K</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Kansas</td>
							<td>10</td>
							<td>Sumner</td>
							<td>Kansas City</td>
						</tr>
						<tr>
							<td></td>
							<td>208</td>
							<td>Shaw</td>
							<td>Leavenworth</td>
						</tr>
						<tr>
							<td></td>
							<td>321</td>
							<td>Fort Pillow</td>
							<td>Topeka</td>
						</tr>
						<tr>
							<td></td>
							<td>365</td>
							<td>Walker</td>
							<td>Lawrence</td>
						</tr>
						<tr>
							<td></td>
							<td>486</td>
							<td>Steele</td>
							<td>Fort Scott</td>
						</tr>
						<tr>
							<td>Kentucky</td>
							<td>10</td>
							<td>Rouseau</td>
							<td>Louisville</td>
						</tr>
						<tr>
							<td></td>
							<td>15</td>
							<td>Jackson</td>
							<td>Carlisle</td>
						</tr>
						<tr>
							<td></td>
							<td>18</td>
							<td>Johnson</td>
							<td>Round Hill</td>
						</tr>
						<tr>
							<td></td>
							<td>32</td>
							<td>Fremont</td>
							<td>Midway</td>
						</tr>
						<tr>
							<td></td>
							<td>43</td>
							<td>Blackburn</td>
							<td>Covington</td>
						</tr>
						<tr>
							<td></td>
							<td>44</td>
							<td>Monroe</td>
							<td>Frankfurt</td>
						</tr>
						<tr>
							<td></td>
							<td>45</td>
							<td>Bacon</td>
							<td>Hopkinsville</td>
						</tr>
						<tr>
							<td></td>
							<td>48</td>
							<td>Smith</td>
							<td>Somerset</td>
						</tr>
						<tr>
							<td></td>
							<td>61</td>
							<td>Sumner</td>
							<td>Lexington</td>
						</tr>
						<tr>
							<td></td>
							<td>68</td>
							<td>Brown</td>
							<td>Paris</td>
						</tr>
						<tr>
							<td></td>
							<td>88</td>
							<td>Hanway</td>
							<td>Bowling Green</td>
						</tr>
						<tr>
							<td></td>
							<td>107</td>
							<td>Martin</td>
							<td>Central City</td>
						</tr>
						<tr>
							<td></td>
							<td>112</td>
							<td>Shaw</td>
							<td>Henderson</td>
						</tr>
						<tr>
							<td></td>
							<td>125</td>
							<td>Young</td>
							<td>Danville</td>
						</tr>
						<tr>
							<td></td>
							<td>130</td>
							<td>Sedgewick</td>
							<td>Richmond</td>
						</tr>
						<tr>
							<td></td>
							<td>142</td>
							<td>Miller</td>
							<td>Nicholasville</td>
						</tr>
						<tr>
							<td></td>
							<td>146</td>
							<td>Terrell</td>
							<td>Harrodsburg</td>
						</tr>
						<tr>
							<td></td>
							<td>156</td>
							<td>Delany</td>
							<td>Louisville</td>
						</tr>
						<tr>
							<td></td>
							<td>166</td>
							<td>McKenevan</td>
							<td>Maysville</td>
						</tr>
						<tr>
							<td></td>
							<td>167</td>
							<td>Connors</td>
							<td>Bardstown</td>
						</tr>
						<tr>
							<td></td>
							<td>181</td>
							<td>Searcy</td>
							<td>Lawrenceburg</td>
						</tr>
						<tr>
							<td></td>
							<td>192</td>
							<td>Douglass</td>
							<td>New Castle</td>
						</tr>
						<tr>
							<td></td>
							<td>197</td>
							<td>Fry</td>
							<td>Anchorage</td>
						</tr>
						<tr>
							<td></td>
							<td>200</td>
							<td>Bacon</td>
							<td>Hopkinsville</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="l"></a>L</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Louisiana</td>
							<td>3</td>
							<td>Hamlin</td>
							<td>Baton Rouge</td>
						</tr>
						<tr>
							<td></td>
							<td>4</td>
							<td>Lincoln</td>
							<td>Thibodeaux</td>
						</tr>
						<tr>
							<td></td>
							<td>9</td>
							<td>Callioux</td>
							<td>New Orleans</td>
						</tr>
						<tr>
							<td></td>
							<td>10</td>
							<td>Bassett</td>
							<td>New Orleans</td>
						</tr>
						<tr>
							<td></td>
							<td>11</td>
							<td>Grant</td>
							<td>New Orleans</td>
						</tr>
						<tr>
							<td></td>
							<td>12</td>
							<td>Crowder</td>
							<td>New Orleans</td>
						</tr>
						<tr>
							<td></td>
							<td>13</td>
							<td>Sheridan</td>
							<td>New Orleans</td>
						</tr>
						<tr>
							<td></td>
							<td>14</td>
							<td>Orillion</td>
							<td>New Orleans</td>
						</tr>
						<tr>
							<td></td>
							<td>15</td>
							<td>Ellsworth</td>
							<td>New Orleans</td>
						</tr>
						<tr>
							<td></td>
							<td>18</td>
							<td>Shaw</td>
							<td>New Orleans</td>
						</tr>
						<tr>
							<td></td>
							<td>19</td>
							<td>Garfield</td>
							<td>Shrevport</td>
						</tr>
						<tr>
							<td></td>
							<td>20</td>
							<td>Delany</td>
							<td>St. Bernard</td>
						</tr>
						<tr>
							<td></td>
							<td>23</td>
							<td>Brownlow</td>
							<td>Vidalia</td>
						</tr>
						<tr>
							<td></td>
							<td>26</td>
							<td>Morton</td>
							<td>Cheatham</td>
						</tr>
						<tr>
							<td></td>
							<td>27</td>
							<td>Custor</td>
							<td>Port Hudson</td>
						</tr>
						<tr>
							<td></td>
							<td>31</td>
							<td>Hayes</td>
							<td>Jesuits' Bend</td>
						</tr>
						<tr>
							<td></td>
							<td>33</td>
							<td>Lynch</td>
							<td>Port Gibson</td>
						</tr>
						<tr>
							<td></td>
							<td>34</td>
							<td>Lake Providence</td>
							<td>Lake Providence</td>
						</tr>
						<tr>
							<td></td>
							<td>35</td>
							<td>Phelps</td>
							<td>Lafayette</td>
						</tr>
						<tr>
							<td></td>
							<td>37</td>
							<td>Canby</td>
							<td>Houma</td>
						</tr>
						<tr>
							<td></td>
							<td>39</td>
							<td>Fairchild Bayou</td>
							<td>Goula</td>
						</tr>
						<tr>
							<td></td>
							<td>40</td>
							<td>McKinley</td>
							<td>Port Allen</td>
						</tr>
						<tr>
							<td></td>
							<td>41</td>
							<td>Plaquemine</td>
							<td>Plaquemine</td>
						</tr>
						<tr>
							<td></td>
							<td>48</td>
							<td>Wilson</td>
							<td>Alexandria</td>
						</tr>
						<tr>
							<td></td>
							<td>49</td>
							<td>Thomas</td>
							<td>Donaldson Ville</td>
						</tr>
						<tr>
							<td></td>
							<td>51</td>
							<td>Butler</td>
							<td>Boutte</td>
						</tr>
						<tr>
							<td></td>
							<td>52</td>
							<td>Pearsall</td>
							<td>St. Martinsville</td>
						</tr>
						<tr>
							<td></td>
							<td>53</td>
							<td>Sherman</td>
							<td>Franklin</td>
						</tr>
						<tr>
							<td></td>
							<td>56</td>
							<td>Shaw</td>
							<td>Iberia</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="m"></a>M</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Maryland</td>
							<td>7</td>
							<td>Lincoln</td>
							<td>Baltimore</td>
						</tr>
						<tr>
							<td></td>
							<td>12</td>
							<td>Sheridan</td>
							<td>Annapolis</td>
						</tr>
						<tr>
							<td></td>
							<td>16</td>
							<td>Guy</td>
							<td>Baltimore</td>
						</tr>
						<tr>
							<td></td>
							<td>19</td>
							<td>Ellsworth</td>
							<td>Baltimore</td>
						</tr>
						<tr>
							<td></td>
							<td>23</td>
							<td>Logan</td>
							<td>Baltimore</td>
						</tr>
						<tr>
							<td></td>
							<td>25</td>
							<td>Sumner</td>
							<td>Chestertown</td>
						</tr>
						<tr>
							<td></td>
							<td>26</td>
							<td>Brown</td>
							<td>Cambridge</td>
						</tr>
						<tr>
							<td></td>
							<td>31</td>
							<td>Lyon</td>
							<td>Hagerstown</td>
						</tr>
						<tr>
							<td></td>
							<td>33</td>
							<td>King</td>
							<td>Baltimore</td>
						</tr>
						<tr>
							<td></td>
							<td>34</td>
							<td>Kilpatrick</td>
							<td>Frederick</td>
						</tr>
						<tr>
							<td></td>
							<td>40</td>
							<td>Stevens</td>
							<td>New Windsor</td>
						</tr>
						<tr>
							<td></td>
							<td>51</td>
							<td>Mead</td>
							<td>Berlin</td>
						</tr>
						<tr>
							<td></td>
							<td>54</td>
							<td>New Shining Light</td>
							<td>Tyaskin</td>
						</tr>
						<tr>
							<td></td>
							<td>55</td>
							<td>Choate</td>
							<td>Ridge</td>
						</tr>
						<tr>
							<td></td>
							<td>56</td>
							<td>Goldsborough</td>
							<td>Centerville</td>
						</tr>
						<tr>
							<td></td>
							<td>60</td>
							<td>Butler</td>
							<td>Princess Anne</td>
						</tr>
						<tr>
							<td></td>
							<td>61</td>
							<td>Johnson</td>
							<td>Tunis Mills</td>
						</tr>
						<tr>
							<td></td>
							<td>62</td>
							<td>Morris</td>
							<td>Salisbury</td>
						</tr>
						<tr>
							<td></td>
							<td>63</td>
							<td>Graper</td>
							<td>Fishing Point</td>
						</tr>
						<tr>
							<td></td>
							<td>64</td>
							<td>Ames</td>
							<td>Millington</td>
						</tr>
						<tr>
							<td></td>
							<td>68</td>
							<td>Armstrong</td>
							<td>Pocomoke City</td>
						</tr>
						<tr>
							<td></td>
							<td>70</td>
							<td>Horner</td>
							<td>Rockville</td>
						</tr>
						<tr>
							<td></td>
							<td>82</td>
							<td>Birney</td>
							<td>Baltimore</td>
						</tr>
						<tr>
							<td>Massachusetts</td>
							<td>134</td>
							<td>Bell</td>
							<td>Boston</td>
						</tr>
						<tr>
							<td></td>
							<td>146</td>
							<td>Shaw</td>
							<td>New Bedford</td>
						</tr>
						<tr>
							<td>Michigan</td>
							<td>184</td>
							<td>Brown</td>
							<td>Detroit</td>
						</tr>
						<tr>
							<td></td>
							<td>341</td>
							<td>Artis</td>
							<td>Calvin</td>
						</tr>
						<tr>
							<td>Mississippi</td>
							<td>2</td>
							<td>Sherman</td>
							<td>Belleville</td>
						</tr>
						<tr>
							<td></td>
							<td>8</td>
							<td>Cady</td>
							<td>Jackson</td>
						</tr>
						<tr>
							<td></td>
							<td>16</td>
							<td>Ransom</td>
							<td>Natchez</td>
						</tr>
						<tr>
							<td></td>
							<td>17</td>
							<td>Elliot</td>
							<td>Vicksburg</td>
						</tr>
						<tr>
							<td></td>
							<td>22</td>
							<td>Edwards</td>
							<td>Vicksburg</td>
						</tr>
						<tr>
							<td></td>
							<td>25</td>
							<td>Greenville</td>
							<td>Greenville</td>
						</tr>
						<tr>
							<td></td>
							<td>28</td>
							<td>Ullman</td>
							<td>Chatham</td>
						</tr>
						<tr>
							<td></td>
							<td>32</td>
							<td>Douglass</td>
							<td>Warrenton</td>
						</tr>
						<tr>
							<td></td>
							<td>33</td>
							<td>Lynch</td>
							<td>Port Gibson</td>
						</tr>
						<tr>
							<td></td>
							<td>38</td>
							<td>Duncansby</td>
							<td>Duncansby</td>
						</tr>
						<tr>
							<td></td>
							<td>42</td>
							<td>Osterhause</td>
							<td>Edwards</td>
						</tr>
						<tr>
							<td></td>
							<td>44</td>
							<td>Ebenezer</td>
							<td>Ebenezer</td>
						</tr>
						<tr>
							<td></td>
							<td>46</td>
							<td>Allen</td>
							<td>Glen Allen</td>
						</tr>
						<tr>
							<td></td>
							<td>47</td>
							<td>Vandergriff</td>
							<td>Summit</td>
						</tr>
						<tr>
							<td></td>
							<td>50</td>
							<td>Leland</td>
							<td>Leland</td>
						</tr>
						<tr>
							<td></td>
							<td>55</td>
							<td>Smith</td>
							<td>Horn Lake</td>
						</tr>
						<tr>
							<td>Missouri</td>
							<td>42</td>
							<td>Candler</td>
							<td>Macon</td>
						</tr>
						<tr>
							<td></td>
							<td>295</td>
							<td>Collie</td>
							<td>Lexington</td>
						</tr>
						<tr>
							<td></td>
							<td>343</td>
							<td>R. G. Shaw</td>
							<td>St. Louis</td>
						</tr>
						<tr>
							<td></td>
							<td>363</td>
							<td>Capitol City</td>
							<td>Jefferson City</td>
						</tr>
						<tr>
							<td></td>
							<td>418</td>
							<td>Clay Shaw</td>
							<td>Sedalia</td>
						</tr>
						<tr>
							<td></td>
							<td>452</td>
							<td>Tipton</td>
							<td>Tipton</td>
						</tr>
						<tr>
							<td></td>
							<td>459</td>
							<td>Whaling</td>
							<td>St. Joseph</td>
						</tr>
						<tr>
							<td></td>
							<td>539</td>
							<td>Perril</td>
							<td>Moberly</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="n"></a>N</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>New Jersey</td>
							<td>51</td>
							<td>Robeson</td>
							<td>Camden</td>
						</tr>
						<tr>
							<td></td>
							<td>53</td>
							<td>Delaney</td>
							<td>Atlantic City</td>
						</tr>
						<tr>
							<td></td>
							<td>56</td>
							<td>Hamilton</td>
							<td>Trenton</td>
						</tr>
						<tr>
							<td></td>
							<td>65</td>
							<td>Tucker</td>
							<td>Newark</td>
						</tr>
						<tr>
							<td></td>
							<td>80</td>
							<td>Shaw</td>
							<td>Moorestown</td>
						</tr>
						<tr>
							<td></td>
							<td>95</td>
							<td>Birney</td>
							<td>Red Bank</td>
						</tr>
						<tr>
							<td></td>
							<td>105</td>
							<td>Hunter</td>
							<td>Princeton</td>
						</tr>
						<tr>
							<td></td>
							<td>119</td>
							<td>Callioux</td>
							<td>Asbury Park</td>
						</tr>
						<tr>
							<td>New York</td>
							<td>207</td>
							<td>Garrison</td>
							<td>New York</td>
						</tr>
						<tr>
							<td></td>
							<td>234</td>
							<td>Andrew</td>
							<td>New York</td>
						</tr>
						<tr>
							<td></td>
							<td>255</td>
							<td>Stevens</td>
							<td>New York</td>
						</tr>
						<tr>
							<td></td>
							<td>620</td>
							<td>Beecher</td>
							<td>Brooklyn</td>
						</tr>
						<tr>
							<td>North Carolina</td>
							<td>15</td>
							<td>Abbot</td>
							<td>Wilmington</td>
						</tr>
						<tr>
							<td></td>
							<td>20</td>
							<td>Fletcher</td>
							<td>Elizabeth City</td>
						</tr>
						<tr>
							<td></td>
							<td>22</td>
							<td>Beecher</td>
							<td>Newbern</td>
						</tr>
						<tr>
							<td></td>
							<td>33</td>
							<td>Flusser</td>
							<td>Washington</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="o"></a>O</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Ohio</td>
							<td>244</td>
							<td>Anderson</td>
							<td>Washington Courthouse</td>
						</tr>
						<tr>
							<td></td>
							<td>390</td>
							<td>Stevens</td>
							<td>Cleveland</td>
						</tr>
						<tr>
							<td></td>
							<td>450</td>
							<td>Brown</td>
							<td>Oxford</td>
						</tr>
						<tr>
							<td></td>
							<td>500</td>
							<td>Daniel</td>
							<td>Xenia</td>
						</tr>
						<tr>
							<td></td>
							<td>580</td>
							<td>Shaw</td>
							<td>Cincinnati</td>
						</tr>
						<tr>
							<td></td>
							<td>588</td>
							<td>Wright</td>
							<td>Chillicothe</td>
						</tr>
						<tr>
							<td></td>
							<td>615</td>
							<td>Delany</td>
							<td>Dayton</td>
						</tr>
						<tr>
							<td></td>
							<td>633</td>
							<td>Brown</td>
							<td>Springfield</td>
						</tr>
						<tr>
							<td></td>
							<td>657</td>
							<td>Steele</td>
							<td>Columbus</td>
						</tr>
						<tr>
							<td></td>
							<td>675</td>
							<td>Allen</td>
							<td>Wilmington</td>
						</tr>
						<tr>
							<td></td>
							<td>713</td>
							<td>Jackson</td>
							<td>Ripley</td>
						</tr>
						<tr>
							<td></td>
							<td>716</td>
							<td>Wyatt</td>
							<td>Cirleville</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="p"></a>P</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Pennsylvania</td>
							<td>27</td>
							<td>Jackson</td>
							<td>Philadelphia</td>
						</tr>
						<tr>
							<td></td>
							<td>80</td>
							<td>Bryan</td>
							<td>Philadelphia</td>
						</tr>
						<tr>
							<td></td>
							<td>80</td>
							<td>Shaw</td>
							<td>West Chester</td>
						</tr>
						<tr>
							<td></td>
							<td>103</td>
							<td>Sumner</td>
							<td>Philadelphia</td>
						</tr>
						<tr>
							<td></td>
							<td>130</td>
							<td>Smith</td>
							<td>West Chester</td>
						</tr>
						<tr>
							<td></td>
							<td>138</td>
							<td>Temple</td>
							<td>Kennett Square/Avondale</td>
						</tr>
						<tr>
							<td></td>
							<td>194</td>
							<td>Brown</td>
							<td>Chester</td>
						</tr>
						<tr>
							<td></td>
							<td>206</td>
							<td>Shaw</td>
							<td>Pittsburgh</td>
						</tr>
						<tr>
							<td></td>
							<td>365</td>
							<td>Dawson</td>
							<td>Uniontown</td>
						</tr>
						<tr>
							<td></td>
							<td>369</td>
							<td>Small</td>
							<td>York</td>
						</tr>
						<tr>
							<td></td>
							<td>390</td>
							<td>Fribley</td>
							<td>Williamsport</td>
						</tr>
						<tr>
							<td></td>
							<td>412</td>
							<td>McCorkey</td>
							<td>Delta/Peach Bottom</td>
						</tr>
						<tr>
							<td></td>
							<td>440</td>
							<td>Thompson</td>
							<td>Carlisle</td>
						</tr>
						<tr>
							<td></td>
							<td>444</td>
							<td>Keith</td>
							<td>Wilkes--Barre</td>
						</tr>
						<tr>
							<td></td>
							<td>487</td>
							<td>Roberts</td>
							<td>Christiana</td>
						</tr>
						<tr>
							<td></td>
							<td>494</td>
							<td>Delany</td>
							<td>Chambersburg</td>
						</tr>
						<tr>
							<td></td>
							<td>520</td>
							<td>Stevens</td>
							<td>Harrisburg</td>
						</tr>
						<tr>
							<td></td>
							<td>535</td>
							<td>Jones</td>
							<td>Brownsville</td>
						</tr>
						<tr>
							<td></td>
							<td>577</td>
							<td>Atchenson</td>
							<td>Washington</td>
						</tr>
						<tr>
							<td></td>
							<td>593</td>
							<td>Elliot</td>
							<td>Uniontown</td>
						</tr>
						<tr>
							<td></td>
							<td>607</td>
							<td>Benn</td>
							<td>Lancaster</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="r"></a>R</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Rhode Island</td>
							<td>13</td>
							<td>Ives</td>
							<td>Providence</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="s"></a>S</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>South Carolina</td>
							<td>9</td>
							<td>Hunter</td>
							<td>Beaufort</td>
						</tr>
						<tr>
							<td></td>
							<td>12</td>
							<td>Lincoln</td>
							<td>Hilton Head</td>
						</tr>
						<tr>
							<td></td>
							<td>13</td>
							<td>Reed</td>
							<td>Charleston</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="t"></a>T</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Tennessee</td>
							<td>4</td>
							<td>Lincoln</td>
							<td>Nashville</td>
						</tr>
						<tr>
							<td></td>
							<td>10</td>
							<td>Lathrop</td>
							<td>Pulaski</td>
						</tr>
						<tr>
							<td></td>
							<td>22</td>
							<td>Chickamauga</td>
							<td>Chattanooga</td>
						</tr>
						<tr>
							<td></td>
							<td>26</td>
							<td>Giddings</td>
							<td>Athens</td>
						</tr>
						<tr>
							<td></td>
							<td>66</td>
							<td>Johnsonville</td>
							<td>Clarksville</td>
						</tr>
						<tr>
							<td></td>
							<td>67</td>
							<td>Jonesborough</td>
							<td>Jonesborough</td>
						</tr>
						<tr>
							<td></td>
							<td>80</td>
							<td>Young</td>
							<td>Knoxville</td>
						</tr>
						<tr>
							<td></td>
							<td>86</td>
							<td>Brown</td>
							<td>Memphis</td>
						</tr>
						<tr>
							<td></td>
							<td>102</td>
							<td>Blaine</td>
							<td>Columbia</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_1">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="v"></a>V</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Virginia</td>
							<td>2</td>
							<td>Callioux</td>
							<td>Norfolk</td>
						</tr>
						<tr>
							<td></td>
							<td>4</td>
							<td>Dahlgren</td>
							<td>Norfolk</td>
						</tr>
						<tr>
							<td></td>
							<td>5</td>
							<td>Shaw</td>
							<td>Norfolk</td>
						</tr>
						<tr>
							<td></td>
							<td>7</td>
							<td>Fellows</td>
							<td>Portsmouth</td>
						</tr>
						<tr>
							<td></td>
							<td>8</td>
							<td>Lincoln</td>
							<td>Princess Anne County</td>
						</tr>
						<tr>
							<td></td>
							<td>9</td>
							<td>Garfield</td>
							<td>Hampton</td>
						</tr>
						<tr>
							<td></td>
							<td>11</td>
							<td>Custer</td>
							<td>Richmond</td>
						</tr>
						<tr>
							<td></td>
							<td>12</td>
							<td>Draper</td>
							<td>Deer Creek</td>
						</tr>
						<tr>
							<td></td>
							<td>18</td>
							<td>Grant</td>
							<td>Eastville</td>
						</tr>
						<tr>
							<td></td>
							<td>19</td>
							<td>Sherman</td>
							<td>Savageville</td>
						</tr>
						<tr>
							<td></td>
							<td>21</td>
							<td>Burnside</td>
							<td>Franktown</td>
						</tr>
						<tr>
							<td></td>
							<td>24</td>
							<td>Moore</td>
							<td>Shoulders Hill</td>
						</tr>
						<tr>
							<td></td>
							<td>27</td>
							<td>Tracy</td>
							<td>Berkely</td>
						</tr>
						<tr>
							<td></td>
							<td>28</td>
							<td>Holloway</td>
							<td>Capeville</td>
						</tr>
						<tr>
							<td></td>
							<td>36</td>
							<td>Carter</td>
							<td>Mappsville</td>
						</tr>
						<tr>
							<td></td>
							<td>54</td>
							<td>Steadman</td>
							<td>Petersburg</td>
						</tr>
					</tbody>
				</table>
				<p class="top">
					<a href="#top">Back to top</a>
				</p>
				<h2><a name="appendix_2"></a>Appendix 2 - Integrated GAR Posts</h2>
				<div id="alpha_order">
					<a href="#a2">A</a>
					<a href="#b2">B</a>
					<a href="#c2">C</a>
					<a href="#d2">D</a>
					<a href="#e2">E</a>
					<a href="#f2">F</a>
					<a href="#g2">G</a>
					<a href="#h2">H</a>
					<a href="#i2">I</a>
					<a href="#j2">J</a>
					<a href="#k2">K</a>
					<a href="#l2">L</a>
					<a href="#m2">M</a>
					<a href="#n2">N</a>
					<a href="#o2">O</a>
					<a href="#p2">P</a>
					<a href="#q2">Q</a>
					<a href="#r2">R</a>
					<a href="#s2">S</a>
					<a href="#t2">T</a>
					<a href="#u2">U</a>
					<a href="#v2">V</a>
					<a href="#w2">W</a>
					<a href="#x2">X</a>
					<a href="#y2">Y</a>
					<a href="#z2">Z</a>
				</div>
				<table>
					<thead>
						<th id="state">State</th>
						<th id="post_no">Post No.</th>
						<th id="name">Name</th>
						<th id="location">Location</th>
					</thead>
					<tbody>
						<tr class="alpha_gap">
							<td><a name="c2"></a>C</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>California</td>
							<td>80</td>
							<td>Corinth</td>
							<td>Marysville</td>
						</tr>
						<tr>
							<td>Colorado</td>
							<td>4</td>
							<td>Lincoln</td>
							<td>Denver</td>
						</tr>
						<tr>
							<td></td>
							<td>5</td>
							<td>Lyon</td>
							<td>Boulder</td>
						</tr>
						<tr>
							<td></td>
							<td>7</td>
							<td>Thomas</td>
							<td>Fort Collins</td>
						</tr>
						<tr>
							<td></td>
							<td>8</td>
							<td>Upton</td>
							<td>Pueblo</td>
						</tr>
						<tr>
							<td></td>
							<td>14</td>
							<td>Denver</td>
							<td>Denver</td>
						</tr>
						<tr>
							<td></td>
							<td>22</td>
							<td>Colorado Springs</td>
							<td>Colorado Springs</td>
						</tr>
						<tr>
							<td></td>
							<td>41</td>
							<td>Kilpatrick</td>
							<td>La Junta</td>
						</tr>
						<tr>
							<td></td>
							<td>42</td>
							<td>Veteran</td>
							<td>Denver</td>
						</tr>
						<tr>
							<td></td>
							<td>46</td>
							<td>Farragut</td>
							<td>Denver</td>
						</tr>
						<tr>
							<td></td>
							<td>48</td>
							<td>Colorado City</td>
							<td>Colorado City</td>
						</tr>
						<tr>
							<td></td>
							<td>77</td>
							<td>Laird</td>
							<td>Steamboat Springs</td>
						</tr>
						<tr>
							<td></td>
							<td>85</td>
							<td>Washington</td>
							<td>Denver</td>
						</tr>
						<tr>
							<td>Connecticut</td>
							<td>1</td>
							<td>Sedgewick</td>
							<td>Norwich</td>
						</tr>
						<tr>
							<td></td>
							<td>2</td>
							<td>Lyon</td>
							<td>Hartford</td>
						</tr>
						<tr>
							<td></td>
							<td>3</td>
							<td>Howe</td>
							<td>Bridgeport</td>
						</tr>
						<tr>
							<td></td>
							<td>4</td>
							<td>Drake</td>
							<td>South Manchester</td>
						</tr>
						<tr>
							<td></td>
							<td>5</td>
							<td>Doolittle</td>
							<td>Cheshire</td>
						</tr>
						<tr>
							<td></td>
							<td>8</td>
							<td>Merriam</td>
							<td>Meridian</td>
						</tr>
						<tr>
							<td></td>
							<td>9</td>
							<td>Taintor</td>
							<td>Colchester</td>
						</tr>
						<tr>
							<td></td>
							<td>11</td>
							<td>Stanley</td>
							<td>New Britain</td>
						</tr>
						<tr>
							<td></td>
							<td>12</td>
							<td>Buckingham</td>
							<td>Norwalk</td>
						</tr>
						<tr>
							<td></td>
							<td>13</td>
							<td>Thompson</td>
							<td>Bristol</td>
						</tr>
						<tr>
							<td></td>
							<td>17</td>
							<td>Foote</td>
							<td>New Haven</td>
						</tr>
						<tr>
							<td></td>
							<td>19</td>
							<td>Sedgewick</td>
							<td>Brooklyn</td>
						</tr>
						<tr>
							<td></td>
							<td>24</td>
							<td>Lombard</td>
							<td>Greenwich</td>
						</tr>
						<tr>
							<td></td>
							<td>27</td>
							<td>Kellogg</td>
							<td>Birmingham/Derby</td>
						</tr>
						<tr>
							<td></td>
							<td>30</td>
							<td>Long</td>
							<td>Willimantic</td>
						</tr>
						<tr>
							<td></td>
							<td>36</td>
							<td>Dutton</td>
							<td>Wallingford</td>
						</tr>
						<tr>
							<td></td>
							<td>39</td>
							<td>Van Horn</td>
							<td>Milford</td>
						</tr>
						<tr>
							<td></td>
							<td>43</td>
							<td>Isbell</td>
							<td>Naugatuck</td>
						</tr>
						<tr>
							<td></td>
							<td>47</td>
							<td>Perkins</td>
							<td>New London</td>
						</tr>
						<tr>
							<td></td>
							<td>50</td>
							<td>Tyler</td>
							<td>Hartford</td>
						</tr>
						<tr>
							<td></td>
							<td>52</td>
							<td>Merwin</td>
							<td>New Haven</td>
						</tr>
						<tr>
							<td></td>
							<td>53</td>
							<td>Mansfield</td>
							<td>Middletown</td>
						</tr>
						<tr>
							<td></td>
							<td>55</td>
							<td>Williams</td>
							<td>Mystic</td>
						</tr>
						<tr>
							<td></td>
							<td>59</td>
							<td>Gregory</td>
							<td>Sharon</td>
						</tr>
						<tr>
							<td></td>
							<td>60</td>
							<td>Cowles</td>
							<td>Canaan</td>
						</tr>
						<tr>
							<td></td>
							<td>62</td>
							<td>Burnside</td>
							<td>Unionville</td>
						</tr>
						<tr>
							<td></td>
							<td>65</td>
							<td>Rodman</td>
							<td>East Hartford</td>
						</tr>
						<tr>
							<td></td>
							<td>71</td>
							<td>Burpee</td>
							<td>Rockville</td>
						</tr>
						<tr>
							<td></td>
							<td>72</td>
							<td>Chapman</td>
							<td>Westbrook</td>
						</tr>
						<tr>
							<td></td>
							<td>75</td>
							<td>Redshaw</td>
							<td>Anosonia</td>
						</tr>
						<tr>
							<td></td>
							<td>77</td>
							<td>Kilborn</td>
							<td>Central Village</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_2">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="d2"></a>D</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Dakota</td>
							<td>47</td>
							<td>Sturgis</td>
							<td>Fort Meade</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_2">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="i2"></a>I</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Illinois</td>
							<td>1</td>
							<td>Nevius</td>
							<td>Rockford</td>
						</tr>
						<tr>
							<td></td>
							<td>6</td>
							<td>Bartleson</td>
							<td>Joliet</td>
						</tr>
						<tr>
							<td></td>
							<td>45</td>
							<td>Shields</td>
							<td>Galesburg</td>
						</tr>
						<tr>
							<td></td>
							<td>48</td>
							<td>Batavia</td>
							<td>Batavia</td>
						</tr>
						<tr>
							<td></td>
							<td>49</td>
							<td>Veteran</td>
							<td>Elgin</td>
						</tr>
						<tr>
							<td></td>
							<td>67</td>
							<td>Bryner</td>
							<td>Peoria</td>
						</tr>
						<tr>
							<td></td>
							<td>68</td>
							<td>Streator</td>
							<td>Streator</td>
						</tr>
						<tr>
							<td></td>
							<td>70</td>
							<td>Lott</td>
							<td>Gibson City</td>
						</tr>
						<tr>
							<td></td>
							<td>71</td>
							<td>Estill</td>
							<td>Petersburg</td>
						</tr>
						<tr>
							<td></td>
							<td>75</td>
							<td>Weider</td>
							<td>Fairbury</td>
						</tr>
						<tr>
							<td></td>
							<td>103</td>
							<td>McDonough</td>
							<td>Macomb</td>
						</tr>
						<tr>
							<td></td>
							<td>105</td>
							<td>Dickey</td>
							<td>Pontiac</td>
						</tr>
						<tr>
							<td></td>
							<td>106</td>
							<td>Loomis</td>
							<td>Du Quoin</td>
						</tr>
						<tr>
							<td></td>
							<td>123</td>
							<td>Duvall</td>
							<td>Mason City</td>
						</tr>
						<tr>
							<td></td>
							<td>128</td>
							<td>Worthen</td>
							<td>Murphysboro</td>
						</tr>
						<tr>
							<td></td>
							<td>129</td>
							<td>Black Eagle</td>
							<td>Urbana</td>
						</tr>
						<tr>
							<td></td>
							<td>138</td>
							<td>Hall</td>
							<td>Shelbyville</td>
						</tr>
						<tr>
							<td></td>
							<td>140</td>
							<td>Nodine</td>
							<td>Champaign</td>
						</tr>
						<tr>
							<td></td>
							<td>141</td>
							<td>Dunham</td>
							<td>Decatur</td>
						</tr>
						<tr>
							<td></td>
							<td>157</td>
							<td>Lowry</td>
							<td>Clinton</td>
						</tr>
						<tr>
							<td></td>
							<td>174</td>
							<td>Van Vleck</td>
							<td>Bushnell</td>
						</tr>
						<tr>
							<td></td>
							<td>176</td>
							<td>Washington Alexander</td>
							<td>Bethany</td>
						</tr>
						<tr>
							<td></td>
							<td>182</td>
							<td>Myers</td>
							<td>Lincoln</td>
						</tr>
						<tr>
							<td></td>
							<td>209</td>
							<td>Driskell</td>
							<td>Paris</td>
						</tr>
						<tr>
							<td></td>
							<td>219</td>
							<td>Cowens</td>
							<td>Pinckneyville</td>
						</tr>
						<tr>
							<td></td>
							<td>243</td>
							<td>Buford</td>
							<td>Rock Island</td>
						</tr>
						<tr>
							<td></td>
							<td>296</td>
							<td>Carmi</td>
							<td>Carmi</td>
						</tr>
						<tr>
							<td></td>
							<td>301</td>
							<td>Colby</td>
							<td>Greenville</td>
						</tr>
						<tr>
							<td></td>
							<td>312</td>
							<td>Graham</td>
							<td>Moline</td>
						</tr>
						<tr>
							<td></td>
							<td>326</td>
							<td>Atlanta</td>
							<td>Atlanta</td>
						</tr>
						<tr>
							<td></td>
							<td>327</td>
							<td>Wright</td>
							<td>Toulon</td>
						</tr>
						<tr>
							<td></td>
							<td>330</td>
							<td>McClanahan</td>
							<td>Monmouth</td>
						</tr>
						<tr>
							<td></td>
							<td>439</td>
							<td>Cobden</td>
							<td>Cobden</td>
						</tr>
						<tr>
							<td></td>
							<td>442</td>
							<td>Carlin</td>
							<td>Carrolton</td>
						</tr>
						<tr>
							<td></td>
							<td>443</td>
							<td>Hecker</td>
							<td>Belleville</td>
						</tr>
						<tr>
							<td></td>
							<td>444</td>
							<td>Meade</td>
							<td>Chicago</td>
						</tr>
						<tr>
							<td></td>
							<td>454</td>
							<td>Newell</td>
							<td>Harrisburg</td>
						</tr>
						<tr>
							<td></td>
							<td>461</td>
							<td>Edwardsville</td>
							<td>Edwardsville</td>
						</tr>
						<tr>
							<td></td>
							<td>468</td>
							<td>Naper/Napier</td>
							<td>Downer's Grove</td>
						</tr>
						<tr>
							<td></td>
							<td>534</td>
							<td>Hubbard</td>
							<td>Collinsville</td>
						</tr>
						<tr>
							<td></td>
							<td>600</td>
							<td>Crabtree</td>
							<td>Walnut Hill</td>
						</tr>
						<tr>
							<td></td>
							<td>613</td>
							<td>Vlerebome</td>
							<td>Buffalo</td>
						</tr>
						<tr>
							<td></td>
							<td>623</td>
							<td>Jones</td>
							<td>Vernon</td>
						</tr>
						<tr>
							<td></td>
							<td>628</td>
							<td>Shepherd</td>
							<td>Quincy</td>
						</tr>
						<tr>
							<td></td>
							<td>724</td>
							<td>Harvey</td>
							<td>Harvey</td>
						</tr>
						<tr>
							<td></td>
							<td>771</td>
							<td>Cain</td>
							<td>Carrier's Mills</td>
						</tr>
						<tr>
							<td></td>
							<td>786</td>
							<td>Hovey</td>
							<td>Normal</td>
						</tr>
						<tr>
							<td></td>
							<td>792</td>
							<td>Lawton</td>
							<td>Danville</td>
						</tr>
						<tr>
							<td>Indiana</td>
							<td>1</td>
							<td>Morton</td>
							<td>Terre Haute</td>
						</tr>
						<tr>
							<td></td>
							<td>6</td>
							<td>Emmett</td>
							<td>Wabash</td>
						</tr>
						<tr>
							<td></td>
							<td>7</td>
							<td>McPherson</td>
							<td>Crawfordsville</td>
						</tr>
						<tr>
							<td></td>
							<td>8</td>
							<td>Auten</td>
							<td>South Bend</td>
						</tr>
						<tr>
							<td></td>
							<td>15</td>
							<td>Morgan/Merchant</td>
							<td>Petersburg</td>
						</tr>
						<tr>
							<td></td>
							<td>16</td>
							<td>Davis</td>
							<td>Vincennes</td>
						</tr>
						<tr>
							<td></td>
							<td>18</td>
							<td>Dumont</td>
							<td>Shelbyville</td>
						</tr>
						<tr>
							<td></td>
							<td>30</td>
							<td>Harrison</td>
							<td>Kokomo</td>
						</tr>
						<tr>
							<td></td>
							<td>36</td>
							<td>McKeehan</td>
							<td>North Vernon</td>
						</tr>
						<tr>
							<td></td>
							<td>40</td>
							<td>Bass</td>
							<td>Fort Wayne</td>
						</tr>
						<tr>
							<td></td>
							<td>55</td>
							<td>Meredith</td>
							<td>Richmond</td>
						</tr>
						<tr>
							<td></td>
							<td>56</td>
							<td>Reyburn</td>
							<td>Peru</td>
						</tr>
						<tr>
							<td></td>
							<td>78</td>
							<td>Williams</td>
							<td>Muncie</td>
						</tr>
						<tr>
							<td></td>
							<td>81</td>
							<td>Wolfe</td>
							<td>Rushville</td>
						</tr>
						<tr>
							<td></td>
							<td>85</td>
							<td>Slocum</td>
							<td>Bloomington</td>
						</tr>
						<tr>
							<td></td>
							<td>89</td>
							<td>Huff</td>
							<td>Lawrenceburg/Aurora</td>
						</tr>
						<tr>
							<td></td>
							<td>90</td>
							<td>Howell</td>
							<td>Goshen</td>
						</tr>
						<tr>
							<td></td>
							<td>92</td>
							<td>Dunbar</td>
							<td>Greenfield</td>
						</tr>
						<tr>
							<td></td>
							<td>103</td>
							<td>Smith</td>
							<td>Sheridan</td>
						</tr>
						<tr>
							<td></td>
							<td>119</td>
							<td>Rader</td>
							<td>Middletown</td>
						</tr>
						<tr>
							<td></td>
							<td>126</td>
							<td>Connersville</td>
							<td>Connersville</td>
						</tr>
						<tr>
							<td></td>
							<td>127</td>
							<td>Wadsworth</td>
							<td>Franklin</td>
						</tr>
						<tr>
							<td></td>
							<td>128</td>
							<td>Houghton</td>
							<td>Mishawaka</td>
						</tr>
						<tr>
							<td></td>
							<td>131</td>
							<td>Coulter</td>
							<td>Russiaville</td>
						</tr>
						<tr>
							<td></td>
							<td>133</td>
							<td>Lookout</td>
							<td>Noblesville</td>
						</tr>
						<tr>
							<td></td>
							<td>148</td>
							<td>Leonard</td>
							<td>New Castle</td>
						</tr>
						<tr>
							<td></td>
							<td>154</td>
							<td>Bailey</td>
							<td>Portland</td>
						</tr>
						<tr>
							<td></td>
							<td>164</td>
							<td>Ogden</td>
							<td>Danville</td>
						</tr>
						<tr>
							<td></td>
							<td>179</td>
							<td>Cambridge City</td>
							<td>Cambridge City</td>
						</tr>
						<tr>
							<td></td>
							<td>198</td>
							<td>Shiloh Field</td>
							<td>Elkhart</td>
						</tr>
						<tr>
							<td></td>
							<td>230</td>
							<td>Henry</td>
							<td>Pendleton</td>
						</tr>
						<tr>
							<td></td>
							<td>238</td>
							<td>Hackleman</td>
							<td>Hackleman</td>
						</tr>
						<tr>
							<td></td>
							<td>240</td>
							<td>Fairfax</td>
							<td>Westfield</td>
						</tr>
						<tr>
							<td></td>
							<td>244</td>
							<td>May</td>
							<td>Anderson</td>
						</tr>
						<tr>
							<td></td>
							<td>247</td>
							<td>Newland</td>
							<td>Bedford</td>
						</tr>
						<tr>
							<td></td>
							<td>259</td>
							<td>Burch</td>
							<td>Arthur</td>
						</tr>
						<tr>
							<td></td>
							<td>271</td>
							<td>Wayne</td>
							<td>Fort Wayne</td>
						</tr>
						<tr>
							<td></td>
							<td>359</td>
							<td>Miller</td>
							<td>Windfall</td>
						</tr>
						<tr>
							<td></td>
							<td>360</td>
							<td>Rayl</td>
							<td>Spiceland</td>
						</tr>
						<tr>
							<td></td>
							<td>410</td>
							<td>Leslie</td>
							<td>Seelyville</td>
						</tr>
						<tr>
							<td></td>
							<td>445</td>
							<td>Rotramel</td>
							<td>Carlisle</td>
						</tr>
						<tr>
							<td></td>
							<td>515</td>
							<td>Thomas</td>
							<td>Paris</td>
						</tr>
						<tr>
							<td></td>
							<td>520</td>
							<td>Cockrum</td>
							<td>Oakland City</td>
						</tr>
						<tr>
							<td></td>
							<td>546</td>
							<td>Bennett</td>
							<td>Marion</td>
						</tr>
						<tr>
							<td>Iowa</td>
							<td>1</td>
							<td>Wentz</td>
							<td>Davenport</td>
						</tr>
						<tr>
							<td></td>
							<td>6</td>
							<td>Rice</td>
							<td>Atlantic</td>
						</tr>
						<tr>
							<td></td>
							<td>7</td>
							<td>Kinsman</td>
							<td>Des Moines</td>
						</tr>
						<tr>
							<td></td>
							<td>8</td>
							<td>Iowa City</td>
							<td>Iowa City</td>
						</tr>
						<tr>
							<td></td>
							<td>11</td>
							<td>Warren</td>
							<td>Clarinda</td>
						</tr>
						<tr>
							<td></td>
							<td>12</td>
							<td>Crocker</td>
							<td>Des Moines</td>
						</tr>
						<tr>
							<td></td>
							<td>15</td>
							<td>Kerney</td>
							<td>Glenwood</td>
						</tr>
						<tr>
							<td></td>
							<td>19</td>
							<td>Strong</td>
							<td>Fairfield</td>
						</tr>
						<tr>
							<td></td>
							<td>20</td>
							<td>McFarland</td>
							<td>Mt. Pleasant</td>
						</tr>
						<tr>
							<td></td>
							<td>22</td>
							<td>Smith/Hancock</td>
							<td>Sioux City</td>
						</tr>
						<tr>
							<td></td>
							<td>39</td>
							<td>Myers</td>
							<td>Greenfield</td>
						</tr>
						<tr>
							<td></td>
							<td>40</td>
							<td>Kearney</td>
							<td>Oskaloosa</td>
						</tr>
						<tr>
							<td></td>
							<td>44</td>
							<td>Davis</td>
							<td>Carroll</td>
						</tr>
						<tr>
							<td></td>
							<td>45</td>
							<td>Mills</td>
							<td>Adel</td>
						</tr>
						<tr>
							<td></td>
							<td>46</td>
							<td>Warner</td>
							<td>Fayette</td>
						</tr>
						<tr>
							<td></td>
							<td>57</td>
							<td>Garfield</td>
							<td>Red Oak</td>
						</tr>
						<tr>
							<td></td>
							<td>67</td>
							<td>Miller</td>
							<td>Boonsboro</td>
						</tr>
						<tr>
							<td></td>
							<td>70</td>
							<td>Lookout</td>
							<td>Dubuque</td>
						</tr>
						<tr>
							<td></td>
							<td>79</td>
							<td>Harper</td>
							<td>Keosauqua</td>
						</tr>
						<tr>
							<td></td>
							<td>88</td>
							<td>Baker</td>
							<td>Clinton</td>
						</tr>
						<tr>
							<td></td>
							<td>107</td>
							<td>Winslow</td>
							<td>Agency</td>
						</tr>
						<tr>
							<td></td>
							<td>108</td>
							<td>White</td>
							<td>Washington</td>
						</tr>
						<tr>
							<td></td>
							<td>110</td>
							<td>Beaver</td>
							<td>Tipton</td>
						</tr>
						<tr>
							<td></td>
							<td>122</td>
							<td>Bashore</td>
							<td>Centerville</td>
						</tr>
						<tr>
							<td></td>
							<td>134</td>
							<td>Griffith</td>
							<td>Oelwein</td>
						</tr>
						<tr>
							<td></td>
							<td>141</td>
							<td>Payne</td>
							<td>Iowa Falls</td>
						</tr>
						<tr>
							<td></td>
							<td>186</td>
							<td>Kellogg</td>
							<td>Seymour</td>
						</tr>
						<tr>
							<td></td>
							<td>231</td>
							<td>Norman</td>
							<td>Muscataine</td>
						</tr>
						<tr>
							<td></td>
							<td>235</td>
							<td>Cook</td>
							<td>Cedar Rapids</td>
						</tr>
						<tr>
							<td></td>
							<td>236</td>
							<td>Fort Donelson</td>
							<td>Fort Dodge</td>
						</tr>
						<tr>
							<td></td>
							<td>254</td>
							<td>King</td>
							<td>Farmington</td>
						</tr>
						<tr>
							<td></td>
							<td>276</td>
							<td>Center</td>
							<td>Randalia</td>
						</tr>
						<tr>
							<td></td>
							<td>312</td>
							<td>Walton</td>
							<td>Garden Grove</td>
						</tr>
						<tr>
							<td></td>
							<td>314</td>
							<td>Hancock</td>
							<td>Belle Plaine</td>
						</tr>
						<tr>
							<td></td>
							<td>337</td>
							<td>Orman</td>
							<td>Albia</td>
						</tr>
						<tr>
							<td></td>
							<td>343</td>
							<td>Dilman</td>
							<td>Toledo</td>
						</tr>
						<tr>
							<td></td>
							<td>345</td>
							<td>Abbott</td>
							<td>West Point</td>
						</tr>
						<tr>
							<td></td>
							<td>438</td>
							<td>Phelps</td>
							<td>Manilla</td>
						</tr>
						<tr>
							<td></td>
							<td>448</td>
							<td>Cantrill</td>
							<td>Gravity</td>
						</tr>
						<tr>
							<td></td>
							<td>452</td>
							<td>Sheridan</td>
							<td>Mashalltown</td>
						</tr>
						<tr>
							<td></td>
							<td>459</td>
							<td>Bonney</td>
							<td>Denmark</td>
						</tr>
						<tr>
							<td></td>
							<td>497</td>
							<td>Tuttle</td>
							<td>South Ottumwa</td>
						</tr>
						<tr>
							<td></td>
							<td>510</td>
							<td>Bryant</td>
							<td>Castana</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_2">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="k2"></a>K</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Kansas</td>
							<td>1</td>
							<td>Lincoln</td>
							<td>Topeka</td>
						</tr>
						<tr>
							<td></td>
							<td>7</td>
							<td>Wadsworth</td>
							<td>Council Grove</td>
						</tr>
						<tr>
							<td></td>
							<td>8</td>
							<td>Larned</td>
							<td>Larned</td>
						</tr>
						<tr>
							<td></td>
							<td>14</td>
							<td>Mead</td>
							<td>Sterling</td>
						</tr>
						<tr>
							<td></td>
							<td>17</td>
							<td>Hooker</td>
							<td>Hutchinson</td>
						</tr>
						<tr>
							<td></td>
							<td>18</td>
							<td>Thomas</td>
							<td>Ottawa</td>
						</tr>
						<tr>
							<td></td>
							<td>22</td>
							<td>Ellsworth</td>
							<td>Ellsworth</td>
						</tr>
						<tr>
							<td></td>
							<td>25</td>
							<td>Garfield</td>
							<td>Wichita</td>
						</tr>
						<tr>
							<td></td>
							<td>36</td>
							<td>Kilpatrick</td>
							<td>Newton</td>
						</tr>
						<tr>
							<td></td>
							<td>38</td>
							<td>Morton</td>
							<td>Wamego</td>
						</tr>
						<tr>
							<td></td>
							<td>52</td>
							<td>Thomas</td>
							<td>Great Bend</td>
						</tr>
						<tr>
							<td></td>
							<td>53</td>
							<td>Henderson</td>
							<td>Frankfort</td>
						</tr>
						<tr>
							<td></td>
							<td>54</td>
							<td>Blair</td>
							<td>Galena</td>
						</tr>
						<tr>
							<td></td>
							<td>55</td>
							<td>Plumb</td>
							<td>Emporia</td>
						</tr>
						<tr>
							<td></td>
							<td>59</td>
							<td>Dix</td>
							<td>Columbus</td>
						</tr>
						<tr>
							<td></td>
							<td>69</td>
							<td>Mitchell</td>
							<td>Osborne</td>
						</tr>
						<tr>
							<td></td>
							<td>75</td>
							<td>Earl</td>
							<td>Eskridge</td>
						</tr>
						<tr>
							<td></td>
							<td>76</td>
							<td>Stockton</td>
							<td>Stockton</td>
						</tr>
						<tr>
							<td></td>
							<td>79</td>
							<td>Brownlow</td>
							<td>Severy</td>
						</tr>
						<tr>
							<td></td>
							<td>80</td>
							<td>Alta Vista</td>
							<td>Alta Vista</td>
						</tr>
						<tr>
							<td></td>
							<td>88</td>
							<td>Sheridan</td>
							<td>Clay Center</td>
						</tr>
						<tr>
							<td></td>
							<td>100</td>
							<td>Gove</td>
							<td>Manhattan</td>
						</tr>
						<tr>
							<td></td>
							<td>104</td>
							<td>Curtis</td>
							<td>Spring Hill</td>
						</tr>
						<tr>
							<td></td>
							<td>116</td>
							<td>Wilderness</td>
							<td>Delphos</td>
						</tr>
						<tr>
							<td></td>
							<td>117</td>
							<td>McCaslin</td>
							<td>Paola</td>
						</tr>
						<tr>
							<td></td>
							<td>118</td>
							<td>Pea Ridge</td>
							<td>Chetopa</td>
						</tr>
						<tr>
							<td></td>
							<td>123</td>
							<td>Baxter Springs</td>
							<td>Baxter Springs</td>
						</tr>
						<tr>
							<td></td>
							<td>127</td>
							<td>Logan</td>
							<td>Salina</td>
						</tr>
						<tr>
							<td></td>
							<td>132</td>
							<td>Junction City</td>
							<td>Junction City</td>
						</tr>
						<tr>
							<td></td>
							<td>142</td>
							<td>Hackleman</td>
							<td>Cherryville</td>
						</tr>
						<tr>
							<td></td>
							<td>145</td>
							<td>Humphrey</td>
							<td>Neodosha</td>
						</tr>
						<tr>
							<td></td>
							<td>147</td>
							<td>Beloit</td>
							<td>Beloit</td>
						</tr>
						<tr>
							<td></td>
							<td>155</td>
							<td>Williams</td>
							<td>Oskaloosa</td>
						</tr>
						<tr>
							<td></td>
							<td>158</td>
							<td>Arkansas City</td>
							<td>Arkansas City</td>
						</tr>
						<tr>
							<td></td>
							<td>171</td>
							<td>Ellis</td>
							<td>Ellis</td>
						</tr>
						<tr>
							<td></td>
							<td>188</td>
							<td>Centralia</td>
							<td>Centralia</td>
						</tr>
						<tr>
							<td></td>
							<td>195</td>
							<td>Wier</td>
							<td>Pardee</td>
						</tr>
						<tr>
							<td></td>
							<td>197</td>
							<td>Trego</td>
							<td>Wakeeney</td>
						</tr>
						<tr>
							<td></td>
							<td>198</td>
							<td>Ransom</td>
							<td>Oberlin</td>
						</tr>
						<tr>
							<td></td>
							<td>244</td>
							<td>Eggleston</td>
							<td>Wichita</td>
						</tr>
						<tr>
							<td></td>
							<td>279</td>
							<td>McLouth</td>
							<td>McLouth</td>
						</tr>
						<tr>
							<td></td>
							<td>281</td>
							<td>McFarland</td>
							<td>Muscotah</td>
						</tr>
						<tr>
							<td></td>
							<td>286</td>
							<td>Cedron</td>
							<td>Cedron</td>
						</tr>
						<tr>
							<td></td>
							<td>316</td>
							<td>Butterfield</td>
							<td>Greensburg</td>
						</tr>
						<tr>
							<td></td>
							<td>322</td>
							<td>Ossawatomie</td>
							<td>Ossawatomie</td>
						</tr>
						<tr>
							<td></td>
							<td>328</td>
							<td>Hale</td>
							<td>Blue Rapids</td>
						</tr>
						<tr>
							<td></td>
							<td>331</td>
							<td>Harker</td>
							<td>Lurray</td>
						</tr>
						<tr>
							<td></td>
							<td>347</td>
							<td>Willis</td>
							<td>Skiddy</td>
						</tr>
						<tr>
							<td></td>
							<td>352</td>
							<td>Tucker</td>
							<td>Garden Plain</td>
						</tr>
						<tr>
							<td></td>
							<td>371</td>
							<td>Mission Ridge</td>
							<td>De Soto</td>
						</tr>
						<tr>
							<td></td>
							<td>375</td>
							<td>Ward</td>
							<td>White Water</td>
						</tr>
						<tr>
							<td></td>
							<td>380</td>
							<td>Brennan</td>
							<td>Leavenworth</td>
						</tr>
						<tr>
							<td></td>
							<td>394</td>
							<td>Lewis</td>
							<td>Dodge City</td>
						</tr>
						<tr>
							<td></td>
							<td>397</td>
							<td>Morton</td>
							<td>Beaumont</td>
						</tr>
						<tr>
							<td></td>
							<td>405</td>
							<td>Oakley</td>
							<td>Oakley</td>
						</tr>
						<tr>
							<td></td>
							<td>415</td>
							<td>Dighton</td>
							<td>Dighton</td>
						</tr>
						<tr>
							<td></td>
							<td>449</td>
							<td>Woodsdale</td>
							<td>Woodsdale</td>
						</tr>
						<tr>
							<td></td>
							<td>453</td>
							<td>Black Eagle</td>
							<td>Horton</td>
						</tr>
						<tr>
							<td></td>
							<td>464</td>
							<td>Hancock</td>
							<td>Emporia</td>
						</tr>
						<tr>
							<td></td>
							<td>467</td>
							<td>Bugh</td>
							<td>Nashville</td>
						</tr>
						<tr>
							<td></td>
							<td>473</td>
							<td>Butler</td>
							<td>Sharon Springs</td>
						</tr>
						<tr>
							<td></td>
							<td>483</td>
							<td>Chevington</td>
							<td>Goddard</td>
						</tr>
						<tr>
							<td>Kentucky</td>
							<td>171</td>
							<td>West</td>
							<td>Berea</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_2">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="m2"></a>M</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Massachusetts</td>
							<td>1</td>
							<td>Rodman</td>
							<td>New Bedford</td>
						</tr>
						<tr>
							<td></td>
							<td>2</td>
							<td>Dahlgren</td>
							<td>South Boston</td>
						</tr>
						<tr>
							<td></td>
							<td>4</td>
							<td>Grant</td>
							<td>Melrose</td>
						</tr>
						<tr>
							<td></td>
							<td>5</td>
							<td>Lander</td>
							<td>Lynn</td>
						</tr>
						<tr>
							<td></td>
							<td>9</td>
							<td>Reno</td>
							<td>Hudson</td>
						</tr>
						<tr>
							<td></td>
							<td>10</td>
							<td>Ward</td>
							<td>Worcester</td>
						</tr>
						<tr>
							<td></td>
							<td>11</td>
							<td>Lincoln</td>
							<td>Charlestown</td>
						</tr>
						<tr>
							<td></td>
							<td>13</td>
							<td>Webster</td>
							<td>Brockton</td>
						</tr>
						<tr>
							<td></td>
							<td>14</td>
							<td>Phillips</td>
							<td>Hopkinton</td>
						</tr>
						<tr>
							<td></td>
							<td>16</td>
							<td>Wilcox</td>
							<td>Springfield</td>
						</tr>
						<tr>
							<td></td>
							<td>19</td>
							<td>Sumner</td>
							<td>Fitchburg</td>
						</tr>
						<tr>
							<td></td>
							<td>22</td>
							<td>Fletcher</td>
							<td>Milford</td>
						</tr>
						<tr>
							<td></td>
							<td>24</td>
							<td>Sprague</td>
							<td>Grafton</td>
						</tr>
						<tr>
							<td></td>
							<td>25</td>
							<td>Legge</td>
							<td>Uxbridge</td>
						</tr>
						<tr>
							<td></td>
							<td>30</td>
							<td>Smart</td>
							<td>Cambridgeport</td>
						</tr>
						<tr>
							<td></td>
							<td>34</td>
							<td>Sheridan</td>
							<td>Salem</td>
						</tr>
						<tr>
							<td></td>
							<td>35</td>
							<td>Winthrop</td>
							<td>Chelsea</td>
						</tr>
						<tr>
							<td></td>
							<td>36</td>
							<td>Gould</td>
							<td>Arlington</td>
						</tr>
						<tr>
							<td></td>
							<td>39</td>
							<td>Needham</td>
							<td>Lawrence</td>
						</tr>
						<tr>
							<td></td>
							<td>39</td>
							<td>Needham</td>
							<td>Lawrence</td>
						</tr>
						<tr>
							<td></td>
							<td>41</td>
							<td>Lyon</td>
							<td>Westfield</td>
						</tr>
						<tr>
							<td></td>
							<td>42</td>
							<td>Butler</td>
							<td>Lowell</td>
						</tr>
						<tr>
							<td></td>
							<td>46</td>
							<td>Borden</td>
							<td>Fall River</td>
						</tr>
						<tr>
							<td></td>
							<td>47</td>
							<td>How</td>
							<td>Haverhill</td>
						</tr>
						<tr>
							<td></td>
							<td>52</td>
							<td>Randall</td>
							<td>Eastondale</td>
						</tr>
						<tr>
							<td></td>
							<td>53</td>
							<td>Stevens</td>
							<td>Leominster</td>
						</tr>
						<tr>
							<td></td>
							<td>56</td>
							<td>Beck</td>
							<td>Cambridge</td>
						</tr>
						<tr>
							<td></td>
							<td>57</td>
							<td>Davis</td>
							<td>East Cambridge</td>
						</tr>
						<tr>
							<td></td>
							<td>59</td>
							<td>Pratt</td>
							<td>Sterling</td>
						</tr>
						<tr>
							<td></td>
							<td>62</td>
							<td>Ward</td>
							<td>Newton</td>
						</tr>
						<tr>
							<td></td>
							<td>63</td>
							<td>Wadsworth</td>
							<td>Natick</td>
						</tr>
						<tr>
							<td></td>
							<td>66</td>
							<td>Lawrence</td>
							<td>Medford</td>
						</tr>
						<tr>
							<td></td>
							<td>68</td>
							<td>Stone</td>
							<td>Cambridge/Dorchester</td>
						</tr>
						<tr>
							<td></td>
							<td>70</td>
							<td>Custer</td>
							<td>Millbury</td>
						</tr>
						<tr>
							<td></td>
							<td>71</td>
							<td>Kilpatrick</td>
							<td>Holyoke</td>
						</tr>
						<tr>
							<td></td>
							<td>72</td>
							<td>St. John Chambre</td>
							<td>Stoughton</td>
						</tr>
						<tr>
							<td></td>
							<td>73</td>
							<td>McPherson</td>
							<td>Abington</td>
						</tr>
						<tr>
							<td></td>
							<td>74</td>
							<td>Hartstuff</td>
							<td>Rockland</td>
						</tr>
						<tr>
							<td></td>
							<td>76</td>
							<td>Collingwood</td>
							<td>Plymouth</td>
						</tr>
						<tr>
							<td></td>
							<td>78</td>
							<td>Russel</td>
							<td>Whitman</td>
						</tr>
						<tr>
							<td></td>
							<td>79</td>
							<td>Sanford</td>
							<td>North Adams</td>
						</tr>
						<tr>
							<td></td>
							<td>80</td>
							<td>Briscoe</td>
							<td>Westborough</td>
						</tr>
						<tr>
							<td></td>
							<td>81</td>
							<td>Patten</td>
							<td>Watertown</td>
						</tr>
						<tr>
							<td></td>
							<td>83</td>
							<td>Wilder</td>
							<td>Hanover</td>
						</tr>
						<tr>
							<td></td>
							<td>86</td>
							<td>Baker</td>
							<td>Northhampton</td>
						</tr>
						<tr>
							<td></td>
							<td>89</td>
							<td>Chipman Jr.</td>
							<td>Beverly</td>
						</tr>
						<tr>
							<td></td>
							<td>91</td>
							<td>Carpenter</td>
							<td>Foxborough</td>
						</tr>
						<tr>
							<td></td>
							<td>92</td>
							<td>Washburn</td>
							<td>Brighton</td>
						</tr>
						<tr>
							<td></td>
							<td>94</td>
							<td>Revere</td>
							<td>Canton</td>
						</tr>
						<tr>
							<td></td>
							<td>99</td>
							<td>Bartlett</td>
							<td>Andover</td>
						</tr>
						<tr>
							<td></td>
							<td>112</td>
							<td>Robinson</td>
							<td>Norwell</td>
						</tr>
						<tr>
							<td></td>
							<td>120</td>
							<td>Garfield</td>
							<td>Andover</td>
						</tr>
						<tr>
							<td></td>
							<td>121</td>
							<td>Ingraham</td>
							<td>Hyde Park</td>
						</tr>
						<tr>
							<td></td>
							<td>124</td>
							<td>Dimick</td>
							<td>East Bridgewater</td>
						</tr>
						<tr>
							<td></td>
							<td>125</td>
							<td>Rockwell</td>
							<td>Pittsfield</td>
						</tr>
						<tr>
							<td></td>
							<td>128</td>
							<td>Appelton</td>
							<td>Ipswich</td>
						</tr>
						<tr>
							<td></td>
							<td>130</td>
							<td>Sargent</td>
							<td>West Medway</td>
						</tr>
						<tr>
							<td></td>
							<td>132</td>
							<td>Chapman</td>
							<td>Sandwich</td>
						</tr>
						<tr>
							<td></td>
							<td>139</td>
							<td>Kingsley</td>
							<td>Somerville</td>
						</tr>
						<tr>
							<td></td>
							<td>140</td>
							<td>Smith</td>
							<td>Athol</td>
						</tr>
						<tr>
							<td></td>
							<td>144</td>
							<td>Carroll</td>
							<td>Dedham</td>
						</tr>
						<tr>
							<td></td>
							<td>147</td>
							<td>Stanton</td>
							<td>Amherst</td>
						</tr>
						<tr>
							<td></td>
							<td>149</td>
							<td>Stearns</td>
							<td>Charleston</td>
						</tr>
						<tr>
							<td></td>
							<td>156</td>
							<td>Perkins</td>
							<td>Everett</td>
						</tr>
						<tr>
							<td></td>
							<td>159</td>
							<td>Hawes</td>
							<td>East Boston</td>
						</tr>
						<tr>
							<td></td>
							<td>165</td>
							<td>Wadsworth</td>
							<td>Duxbury</td>
						</tr>
						<tr>
							<td></td>
							<td>166</td>
							<td>Strong</td>
							<td>Easthampton</td>
						</tr>
						<tr>
							<td></td>
							<td>168</td>
							<td>Ammidown</td>
							<td>Southbridge</td>
						</tr>
						<tr>
							<td></td>
							<td>171</td>
							<td>Johnson</td>
							<td>Northfield</td>
						</tr>
						<tr>
							<td></td>
							<td>173</td>
							<td>Johnson</td>
							<td>Sturbridge</td>
						</tr>
						<tr>
							<td></td>
							<td>178</td>
							<td>Nichols</td>
							<td>Otis</td>
						</tr>
						<tr>
							<td></td>
							<td>187</td>
							<td>Hancock</td>
							<td>Dalton</td>
						</tr>
						<tr>
							<td></td>
							<td>190</td>
							<td>Pierce</td>
							<td>New Bedford</td>
						</tr>
						<tr>
							<td></td>
							<td>191</td>
							<td>Gettysburg</td>
							<td>Boston</td>
						</tr>
						<tr>
							<td></td>
							<td>195</td>
							<td>Parker</td>
							<td>East Pepperell</td>
						</tr>
						<tr>
							<td></td>
							<td>198</td>
							<td>Mount Miller</td>
							<td>Plainfield</td>
						</tr>
						<tr>
							<td></td>
							<td>199</td>
							<td>Eaton</td>
							<td>Revere</td>
						</tr>
						<tr>
							<td></td>
							<td>205</td>
							<td>Bridgewater</td>
							<td>Bridgewater</td>
						</tr>
						<tr>
							<td></td>
							<td>207</td>
							<td>Gardner</td>
							<td>Nantucket</td>
						</tr>
						<tr>
							<td></td>
							<td>209</td>
							<td>Hopkins</td>
							<td>Williamstown</td>
						</tr>
						<tr>
							<td></td>
							<td>210</td>
							<td>Barnard</td>
							<td>Sheffield</td>
						</tr>
						<tr>
							<td>Michigan</td>
							<td>38</td>
							<td>Granger</td>
							<td>East Saginaw</td>
						</tr>
						<tr>
							<td></td>
							<td>45</td>
							<td>Woodbury</td>
							<td>Adrian</td>
						</tr>
						<tr>
							<td></td>
							<td>137</td>
							<td>Welch</td>
							<td>Ann Arbor</td>
						</tr>
						<tr>
							<td></td>
							<td>157</td>
							<td>Anderson</td>
							<td>Cassopolis</td>
						</tr>
						<tr>
							<td></td>
							<td>351</td>
							<td>Allen</td>
							<td>Covert</td>
						</tr>
						<tr>
							<td>Minnesota</td>
							<td>13</td>
							<td>Gorman</td>
							<td>Duluth</td>
						</tr>
						<tr>
							<td></td>
							<td>21</td>
							<td>Ackers</td>
							<td>St. Paul</td>
						</tr>
						<tr>
							<td></td>
							<td>35</td>
							<td>Dagget</td>
							<td>Litchfield</td>
						</tr>
						<tr>
							<td>Missouri</td>
							<td>7</td>
							<td>Custer</td>
							<td>St. Joseph</td>
						</tr>
						<tr>
							<td></td>
							<td>22</td>
							<td>Dix</td>
							<td>Kirksville</td>
						</tr>
						<tr>
							<td></td>
							<td>104</td>
							<td>Nichols</td>
							<td>Gallatin</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_2">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="n2"></a>N</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Nebraska</td>
							<td>7</td>
							<td>Custer</td>
							<td>Omaha</td>
						</tr>
						<tr>
							<td></td>
							<td>25</td>
							<td>Farragut</td>
							<td>Lincoln</td>
						</tr>
						<tr>
							<td></td>
							<td>34</td>
							<td>Sheridan</td>
							<td>Schuyler</td>
						</tr>
						<tr>
							<td></td>
							<td>47</td>
							<td>Heckathorn</td>
							<td>Tecumseh</td>
						</tr>
						<tr>
							<td></td>
							<td>110</td>
							<td>Omaha</td>
							<td>Omaha</td>
						</tr>
						<tr>
							<td></td>
							<td>180</td>
							<td>Steadman</td>
							<td>Ansley</td>
						</tr>
						<tr>
							<td>New York</td>
							<td>41</td>
							<td>Sydney</td>
							<td>Ithaca</td>
						</tr>
						<tr>
							<td></td>
							<td>45</td>
							<td>Crocker</td>
							<td>Auburn</td>
						</tr>
						<tr>
							<td></td>
							<td>83</td>
							<td>Smith</td>
							<td>Norwich</td>
						</tr>
						<tr>
							<td></td>
							<td>160</td>
							<td>Knowlton</td>
							<td>Cazenovia</td>
						</tr>
						<tr>
							<td></td>
							<td>175</td>
							<td>Lockwood</td>
							<td>Port Byron</td>
						</tr>
						<tr>
							<td></td>
							<td>217</td>
							<td>Birney</td>
							<td>Sandy Creek</td>
						</tr>
						<tr>
							<td></td>
							<td>230</td>
							<td>Robinson</td>
							<td>Genoa</td>
						</tr>
						<tr>
							<td></td>
							<td>285</td>
							<td>Brown</td>
							<td>Jamestown</td>
						</tr>
						<tr>
							<td></td>
							<td>300</td>
							<td>Terry</td>
							<td>Amsterdam</td>
						</tr>
						<tr>
							<td></td>
							<td>323</td>
							<td>Spratt</td>
							<td>Watertown</td>
						</tr>
						<tr>
							<td></td>
							<td>496</td>
							<td>Burnett</td>
							<td>Tarrytown</td>
						</tr>
						<tr>
							<td></td>
							<td>514</td>
							<td>Watson</td>
							<td>Catskill</td>
						</tr>
						<tr>
							<td></td>
							<td>558</td>
							<td>Charette</td>
							<td>Warrensburg</td>
						</tr>
						<tr>
							<td></td>
							<td>587</td>
							<td>Collin</td>
							<td>Sandy Hill</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_2">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="o2"></a>O</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Ohio</td>
							<td>1</td>
							<td>McCoy</td>
							<td>Columbus</td>
						</tr>
						<tr>
							<td></td>
							<td>5</td>
							<td>Veteran</td>
							<td>Dayton</td>
						</tr>
						<tr>
							<td></td>
							<td>10</td>
							<td>Trescott</td>
							<td>Salem</td>
						</tr>
						<tr>
							<td></td>
							<td>12</td>
							<td>Buckley</td>
							<td>Akron</td>
						</tr>
						<tr>
							<td></td>
							<td>14</td>
							<td>Ford</td>
							<td>East Toledo</td>
						</tr>
						<tr>
							<td></td>
							<td>15</td>
							<td>Forsyth</td>
							<td>Toledo</td>
						</tr>
						<tr>
							<td></td>
							<td>21</td>
							<td>Hooker</td>
							<td>Mount Vernon</td>
						</tr>
						<tr>
							<td></td>
							<td>27</td>
							<td>Norris</td>
							<td>Fostoria</td>
						</tr>
						<tr>
							<td></td>
							<td>29</td>
							<td>Tod</td>
							<td>Youngstown</td>
						</tr>
						<tr>
							<td></td>
							<td>32</td>
							<td>Rawson</td>
							<td>Fremont</td>
						</tr>
						<tr>
							<td></td>
							<td>36</td>
							<td>Harmon</td>
							<td>Warren</td>
						</tr>
						<tr>
							<td></td>
							<td>50</td>
							<td>Price</td>
							<td>Westerville</td>
						</tr>
						<tr>
							<td></td>
							<td>54</td>
							<td>Stoker</td>
							<td>Findlay</td>
						</tr>
						<tr>
							<td></td>
							<td>65</td>
							<td>Allen</td>
							<td>Elyria</td>
						</tr>
						<tr>
							<td></td>
							<td>81</td>
							<td>Hazlett</td>
							<td>Zanesville</td>
						</tr>
						<tr>
							<td></td>
							<td>98</td>
							<td>Brand</td>
							<td>Urbana</td>
						</tr>
						<tr>
							<td></td>
							<td>99</td>
							<td>Spangler</td>
							<td>Bellaire</td>
						</tr>
						<tr>
							<td></td>
							<td>126</td>
							<td>Cadot</td>
							<td>Galliopolis</td>
						</tr>
						<tr>
							<td></td>
							<td>140</td>
							<td>Rochester</td>
							<td>Logan</td>
						</tr>
						<tr>
							<td></td>
							<td>141</td>
							<td>Memorial</td>
							<td>Cleveland</td>
						</tr>
						<tr>
							<td></td>
							<td>153</td>
							<td>Fowler</td>
							<td>Berlin Heights</td>
						</tr>
						<tr>
							<td></td>
							<td>158</td>
							<td>Alexander</td>
							<td>Piqua</td>
						</tr>
						<tr>
							<td></td>
							<td>159</td>
							<td>Coleman</td>
							<td>Troy</td>
						</tr>
						<tr>
							<td></td>
							<td>164</td>
							<td>Bailey</td>
							<td>Portsmouth</td>
						</tr>
						<tr>
							<td></td>
							<td>165</td>
							<td>Lambert</td>
							<td>Ironton</td>
						</tr>
						<tr>
							<td></td>
							<td>183</td>
							<td>Douglas</td>
							<td>Millbury</td>
						</tr>
						<tr>
							<td></td>
							<td>202</td>
							<td>Armstrong</td>
							<td>Lima</td>
						</tr>
						<tr>
							<td></td>
							<td>238</td>
							<td>Baxter</td>
							<td>Lyons</td>
						</tr>
						<tr>
							<td></td>
							<td>276</td>
							<td>Kelley</td>
							<td>Corning</td>
						</tr>
						<tr>
							<td></td>
							<td>280</td>
							<td>Barnes</td>
							<td>Waverly</td>
						</tr>
						<tr>
							<td></td>
							<td>283</td>
							<td>Stanley</td>
							<td>Forrest</td>
						</tr>
						<tr>
							<td></td>
							<td>293</td>
							<td>Briney</td>
							<td>North Lewisburg</td>
						</tr>
						<tr>
							<td></td>
							<td>313</td>
							<td>Devol</td>
							<td>Carbon Hill</td>
						</tr>
						<tr>
							<td></td>
							<td>315</td>
							<td>Bethel</td>
							<td>Flushing</td>
						</tr>
						<tr>
							<td></td>
							<td>353</td>
							<td>Stevens</td>
							<td>Morrow</td>
						</tr>
						<tr>
							<td></td>
							<td>364</td>
							<td>Lincoln</td>
							<td>Oberlin</td>
						</tr>
						<tr>
							<td></td>
							<td>365</td>
							<td>Smith</td>
							<td>Jackson</td>
						</tr>
						<tr>
							<td></td>
							<td>403</td>
							<td>Austin</td>
							<td>Clevelan</td>
						</tr>
						<tr>
							<td></td>
							<td>406</td>
							<td>Bostwick</td>
							<td>Mount Sterling</td>
						</tr>
						<tr>
							<td></td>
							<td>415</td>
							<td>Cass</td>
							<td>Dresden</td>
						</tr>
						<tr>
							<td></td>
							<td>422</td>
							<td>Welch</td>
							<td>Uhrichsville</td>
						</tr>
						<tr>
							<td></td>
							<td>425</td>
							<td>Livingston</td>
							<td>Richwood</td>
						</tr>
						<tr>
							<td></td>
							<td>441</td>
							<td>Reynolds</td>
							<td>Bellefontaine</td>
						</tr>
						<tr>
							<td></td>
							<td>513</td>
							<td>Crosby</td>
							<td>Broughton</td>
						</tr>
						<tr>
							<td></td>
							<td>537</td>
							<td>Banner</td>
							<td>Springsboro</td>
						</tr>
						<tr>
							<td></td>
							<td>560</td>
							<td>Lewis</td>
							<td>Wilkesville</td>
						</tr>
						<tr>
							<td></td>
							<td>570</td>
							<td>Kimball</td>
							<td>Milford Centre</td>
						</tr>
						<tr>
							<td></td>
							<td>572</td>
							<td>Reed</td>
							<td>Palestine</td>
						</tr>
						<tr>
							<td></td>
							<td>616</td>
							<td>Taylor</td>
							<td>Somerton</td>
						</tr>
						<tr>
							<td></td>
							<td>621</td>
							<td>Andrew Linberry</td>
							<td>Melrose</td>
						</tr>
						<tr>
							<td></td>
							<td>626</td>
							<td>Sisson</td>
							<td>Bidwell</td>
						</tr>
						<tr>
							<td></td>
							<td>643</td>
							<td>Logwood</td>
							<td>Middleport</td>
						</tr>
						<tr>
							<td></td>
							<td>683</td>
							<td>Merchant</td>
							<td>Paulding</td>
						</tr>
						<tr>
							<td></td>
							<td>692</td>
							<td>Climer</td>
							<td>Omega</td>
						</tr>
						<tr>
							<td></td>
							<td>695</td>
							<td>Toland</td>
							<td>Sandusky</td>
						</tr>
						<tr>
							<td></td>
							<td>715</td>
							<td>Volunteer</td>
							<td>Toledo</td>
						</tr>
						<tr>
							<td></td>
							<td>742</td>
							<td>Grosevnor</td>
							<td>Broadwell</td>
						</tr>
						<tr>
							<td>Ontario, Canada</td>
							<td>652</td>
							<td>Hamlin</td>
							<td>London</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_2">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="p2"></a>P</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Pennsylvania</td>
							<td>16</td>
							<td>McLean</td>
							<td>Reading</td>
						</tr>
						<tr>
							<td></td>
							<td>44</td>
							<td>Simpson</td>
							<td>Huntington</td>
						</tr>
						<tr>
							<td></td>
							<td>61</td>
							<td>Chapman</td>
							<td>Mauch Chunk</td>
						</tr>
						<tr>
							<td></td>
							<td>62</td>
							<td>Potts</td>
							<td>Altoona</td>
						</tr>
						<tr>
							<td></td>
							<td>64</td>
							<td>Reno</td>
							<td>Williamsport</td>
						</tr>
						<tr>
							<td></td>
							<td>84</td>
							<td>Thomas</td>
							<td>Lancaster</td>
						</tr>
						<tr>
							<td></td>
							<td>87</td>
							<td>Young</td>
							<td>Allentown</td>
						</tr>
						<tr>
							<td></td>
							<td>95</td>
							<td>Gregg</td>
							<td>Bellefonte</td>
						</tr>
						<tr>
							<td></td>
							<td>100</td>
							<td>New Castle</td>
							<td>New Castle</td>
						</tr>
						<tr>
							<td></td>
							<td>139</td>
							<td>Griffin</td>
							<td>Scranton</td>
						</tr>
						<tr>
							<td></td>
							<td>140</td>
							<td>Lincoln</td>
							<td>Shamokin</td>
						</tr>
						<tr>
							<td></td>
							<td>141</td>
							<td>Melvin</td>
							<td>Bradford</td>
						</tr>
						<tr>
							<td></td>
							<td>151</td>
							<td>Patterson</td>
							<td>Pittsburgh</td>
						</tr>
						<tr>
							<td></td>
							<td>153</td>
							<td>Espy</td>
							<td>Pittsburgh</td>
						</tr>
						<tr>
							<td></td>
							<td>156</td>
							<td>Croll</td>
							<td>Kittaning</td>
						</tr>
						<tr>
							<td></td>
							<td>167</td>
							<td>Evans</td>
							<td>Oil City</td>
						</tr>
						<tr>
							<td></td>
							<td>168</td>
							<td>Billingsley</td>
							<td>California</td>
						</tr>
						<tr>
							<td></td>
							<td>169</td>
							<td>Mercer</td>
							<td>Mercer</td>
						</tr>
						<tr>
							<td></td>
							<td>172</td>
							<td>Jones</td>
							<td>Tyrone</td>
						</tr>
						<tr>
							<td></td>
							<td>176</td>
							<td>Hulings</td>
							<td>Lewistown</td>
						</tr>
						<tr>
							<td></td>
							<td>178</td>
							<td>Bayard</td>
							<td>Belle Vernon</td>
						</tr>
						<tr>
							<td></td>
							<td>182</td>
							<td>Taylor</td>
							<td>Bethlehem</td>
						</tr>
						<tr>
							<td></td>
							<td>208</td>
							<td>Stanton</td>
							<td>New Brighton</td>
						</tr>
						<tr>
							<td></td>
							<td>242</td>
							<td>Brady</td>
							<td>Brookville</td>
						</tr>
						<tr>
							<td></td>
							<td>300</td>
							<td>Heintzelman</td>
							<td>Manheim</td>
						</tr>
						<tr>
							<td></td>
							<td>331</td>
							<td>Pieffer</td>
							<td>Meadville</td>
						</tr>
						<tr>
							<td></td>
							<td>349</td>
							<td>Keenan</td>
							<td>Jersey Shore</td>
						</tr>
						<tr>
							<td></td>
							<td>405</td>
							<td>Reynolds</td>
							<td>Lancaster</td>
						</tr>
						<tr>
							<td></td>
							<td>453</td>
							<td>Four Brothers</td>
							<td>Montrose</td>
						</tr>
						<tr>
							<td></td>
							<td>468</td>
							<td>Ward</td>
							<td>Altoona</td>
						</tr>
						<tr>
							<td></td>
							<td>478</td>
							<td>Nissley</td>
							<td>Mount Joy</td>
						</tr>
						<tr>
							<td></td>
							<td>507</td>
							<td>Elden</td>
							<td>Bendersville</td>
						</tr>
						<tr>
							<td></td>
							<td>541</td>
							<td>Jones</td>
							<td>Southfield</td>
						</tr>
						<tr>
							<td></td>
							<td>544</td>
							<td>Gaston</td>
							<td>Gastonville</td>
						</tr>
						<tr>
							<td></td>
							<td>571</td>
							<td>Hess</td>
							<td>Safe Harbor</td>
						</tr>
						<tr>
							<td></td>
							<td>599</td>
							<td>Reed</td>
							<td>Coatesville</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_2">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="r2"></a>R</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Rhode Island</td>
							<td>5</td>
							<td>Lawton</td>
							<td>Newport</td>
						</tr>
						<tr>
							<td></td>
							<td>16</td>
							<td>Baker</td>
							<td>Wickford</td>
						</tr>
						<tr>
							<td></td>
							<td>18</td>
							<td>Budlong</td>
							<td>Westerly</td>
						</tr>
						<tr>
							<td></td>
							<td>24</td>
							<td>Tobin</td>
							<td>Warrenburg</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><a href="#appendix_2">Back to top</a></td>
						</tr>
						<tr class="alpha_gap">
							<td><a name="t2"></a>T</td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td>Tennessee</td>
							<td>13</td>
							<td>Lane</td>
							<td>Bull's Gap</td>
						</tr>
						<tr>
							<td></td>
							<td>25</td>
							<td>Garfield</td>
							<td>Athens</td>
						</tr>
						<tr>
							<td></td>
							<td>26</td>
							<td>Patton</td>
							<td>Johnson City</td>
						</tr>
						<tr>
							<td></td>
							<td>35</td>
							<td>Jonesborough</td>
							<td>Jonesborough</td>
						</tr>
						<tr>
							<td></td>
							<td>39</td>
							<td>Mcteer</td>
							<td>Ellijoy</td>
						</tr>
						<tr>
							<td></td>
							<td>40</td>
							<td>Cove</td>
							<td>Oak Grove</td>
						</tr>
						<tr>
							<td></td>
							<td>46</td>
							<td>McGuire</td>
							<td>New Market</td>
						</tr>
						<tr>
							<td></td>
							<td>47</td>
							<td>Dyer</td>
							<td>Rutledge</td>
						</tr>
						<tr>
							<td></td>
							<td>58</td>
							<td>Catlett</td>
							<td>Sevierville</td>
						</tr>
						<tr>
							<td></td>
							<td>78</td>
							<td>Fisher</td>
							<td>Knoxville</td>
						</tr>
						<tr>
							<td></td>
							<td>91</td>
							<td>McConnel</td>
							<td>Maryville</td>
						</tr>
						<tr>
							<td></td>
							<td>96</td>
							<td>Stokes</td>
							<td>New Middleton</td>
						</tr>
					</tbody>
				</table>
				<p class="top">
					<a href="#top">Back to top</a>
				</p>
          	</div><!--appendices_container-->         
        </div><!--content_container-->
		<?php
			include_once("footer.php");
		?>
    </div>
</body>
</html>